name: "Podcast Generator"
author: "SK"
description: "Generates feed for podcast from YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
input:
  email:
    description: Commiters email
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: commiters name
    required: true
    default: ${{ github.actor }}